language: python

dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
    - pip install tox-travis
    - pip install codecov
    - sudo apt-get install gdal-bin

script:
    - codecov run tox

notifications:
    email: false

after_success:
  - codecov

