language: python

dist: bionic

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - env: TOXENV=flake8

install:
  - pip install tox-travis
  - pip install codecov
  - sudo apt-get install gdal-bin

script:
  - tox

notifications:
  email: false

after_success:
  - codecov

